### ISSUE TITLE
Calculus and Optimization: a typo

### ISSUE THREAD

**Issue by hamidrezaen** [SharifiZarchi/Introduction_to_Machine_Learning#37]
Chapter_01_Mathematics / Calculus and Optimization
![Screenshot (356)](https://github.com/user-attachments/assets/4a8a6bbd-4657-4643-b5c9-b709eb066fc0)

**Comment by RamtinMoslemi** [comment]
Thanks!

**Comment by Angga499** [comment]
Yes
